language: go
os: linux
dist: xenial

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

go: 1.x

stages:
  - check
  - test
  - build

jobs:
  include:
    - stage: check
      script: make lint
      after_success: skip
    - stage: test
      script: make test
      after_success: if [ -f coverage.out ]; then bash <(curl -s https://codecov.io/bash); fi
    - &build
      stage: build
      env: TARGET=darwin
      script: make build GOOS=$TARGET
      after_success: skip
    - <<: *build
      env: TARGET=linux
    - <<: *build
      env: TARGET=windows
  allow_failures:
    - go: master
  fast_finish: true
